[package]
name = "rs-simple-redis"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
bytes = "1.6.0"
enum_dispatch = "0.3.13"
thiserror = "1.0.58"
lazy_static = "1.4.0"
dashmap = "5.5.3"
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros", "net"] }
tokio-stream = "0.1.15"
tokio-util = { version = "0.7.10", features = ["codec"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
futures = {version = "0.3.30", default-features = false}